version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]

  opensearch:
    image: opensearchproject/opensearch:2.12.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=opensearch
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports: ["9200:9200"]

  docs:
   image: swaggerapi/swagger-ui:latest
   ports: ["8081:8080"]
   environment:
    - API_URL=/openapi.yaml
   volumes:
     - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro


  backend:
    build: ./backend
    env_file:
      - backend/.env
    environment:
      - PORT=5050
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=drishti
    depends_on:
      - mongo
      - opensearch
    ports: ["5050:5050"]
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      - API_BASE_URL=http://backend:5050
    depends_on: [backend]
    ports: ["8501:8501"]
    volumes:
      - ./frontend:/app

  ml:
    build: ./ml
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports: ["8000:8000"]
    volumes:
      - ./ml:/app

  # Low-code workflows / webhooks / schedulers
  n8n:
    image: n8nio/n8n:latest
    ports: ["5678:5678"]
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n

  # Optional local LLM runtime for Llama3/Mistral
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   restart: unless-stopped
  #   ports: ["11434:11434"]
  #   volumes:
  #     - ollama_data:/root/.ollama

volumes:
  n8n_data:
  ollama_data:
